blank_issues_enabled: false
contact_links:
    - name: Github Community Support
      url: https://github.com/Jonak-Adipta-Kalita/JAK-Mobile-App/discussions
      about: Please ask and answer questions here.
    - name: Twitter
      url: https://twitter.com/AdiptaJonak
      about: Get the product updates easily.
