## Issue Template

### Description
[Briefly describe the issue you are facing or the feature you would like to request.]

### Steps to Reproduce (if applicable)
[List the steps to reproduce the issue, including any specific conditions or inputs.]

1. 
2. 
3. 

### Expected Behavior
[Describe what you expected to happen.]

### Actual Behavior
[Describe what actually happened.]

### Screenshots (if applicable)
[Add any relevant screenshots that can help understand the issue.]

### Environment (if applicable)
- Operating System: [e.g., Android, iOS]
- Device Name: [e.g., Samsung Galaxy M30,  IPhone 14 Pro]
- Version: [e.g., Android11, iOS 14]

### Additional Information
[Provide any additional context or details about the issue.]

### Possible Solution (if applicable)
[Suggest a possible solution or approach to resolving the issue.]

